### ISSUE TITLE
IndexOutOfBoundsException - SlidingRootNavLayout.onLayout (SlidingRootNavLayout.java:72)

### ISSUE THREAD

**Issue by peto146** [yarolegovich/SlidingRootNav#19]
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{307be76 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}
       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
       at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1391)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at com.yarolegovich.slidingrootnav.SlidingRootNavLayout.onLayout(SlidingRootNavLayout.java:72)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by bowiechang** [comment]
Did you change the items at the side drawer? You must also change the relevant string array values and the position.

**Comment by peto146** [comment]
Hi, yes, I did, this issue arise just three times, and Im not sure if not
only on emulator, what may be a cause...

Best regards /S pozdravom
Peter Jarinčík,
+421 910 643 544

2017-07-27 10:44 GMT+03:00 bowiechang <notifications@github.com>:

**Comment by yarolegovich** [comment]
That's the problem with your RecyclerView, not the library.
